version: "3.8"
services:
  crypto-app-frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    environment:
      WATCHPACK_POLLING: true
